server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/leyou?characterEncoding=UTF8&serverTimezone=Asia/Shanghai
    username: root
    password: xcx
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
mybatis:
  type-aliases-package: com.leyou.item.pojo
